export const DELETE_PATIENT = 'DELETE_PATIENT';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const CREATE_MEDICAL_DATA = 'CREATE_MEDICAL_DATA';
export const CREATE_PATIENT_PHOTO = 'CREATE_PATIENT_PHOTO';
export const GET_ALL_MEDICAL_DATA = 'GET_ALL_MEDICAL_DATA';
export const GET_ALL_DELETED_PATIENT = 'GET_ALL_DELETED_PATIENT';
export const GET_PATIENT_PHOTO = 'GET_PATIENT_PHOTO';
export const GET_PATIENT = 'GET_PATIENT';

export const SYNCHRO_DELETE_LOCAL_PATIENTS = 'SYNCHRO_DELETE_LOCAL_PATIENTS';
export const SYNCHRO_DELETE_LOCAL_PATIENTS_FAILDED = 'SYNCHRO_DELETE_LOCAL_PATIENTS_FAILDED';

export const SYNCHRO_UPLOAD_LOCAL_PATIENTS = 'SYNCHRO_UPLOAD_LOCAL_PATIENTS';
export const SYNCHRO_UPLOAD_LOCAL_PATIENTS_FAILDED = 'SYNCHRO_UPLOAD_LOCAL_PATIENTS_FAILDED';

export const SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS = 'SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS';
export const SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS_FAILDED = 'SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS_FAILDED';

export const SYNCHRO_DOWNLOAD_ONLINE_PATIENTS = 'SYNCHRO_DOWNLOAD_ONLINE_PATIENTS';
export const SYNCHRO_DOWNLOAD_ONLINE_PATIENTS_FAILDED = 'SYNCHRO_DOWNLOAD_ONLINE_PATIENTS_FAILDED';

export const SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS = 'SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS';
export const SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS_FAILDED = 'SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS_FAILDED';

export const SYNCHRO_FULL_SUCCESS = 'SYNCHRO_FULL_SUCCESS';
export const SYNCHRO_FULL_FAILDED = 'SYNCHRO_FULL_FAILDED';