import { SYNCHRO_DELETE_LOCAL_PATIENTS, SYNCHRO_DELETE_LOCAL_PATIENTS_FAILDED, SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS, SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS_FAILDED, SYNCHRO_DOWNLOAD_ONLINE_PATIENTS, SYNCHRO_DOWNLOAD_ONLINE_PATIENTS_FAILDED, SYNCHRO_FULL_FAILDED, SYNCHRO_FULL_SUCCESS, SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS, SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS_FAILDED, SYNCHRO_UPLOAD_LOCAL_PATIENTS, SYNCHRO_UPLOAD_LOCAL_PATIENTS_FAILDED } from "../Constants/syncAudit";

export type AuditEventType = typeof SYNCHRO_DELETE_LOCAL_PATIENTS |
    typeof SYNCHRO_DELETE_LOCAL_PATIENTS_FAILDED |
    typeof SYNCHRO_UPLOAD_LOCAL_PATIENTS |
    typeof SYNCHRO_UPLOAD_LOCAL_PATIENTS_FAILDED |
    typeof SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS |
    typeof SYNCHRO_UPLOAD_LOCAL_CONSULTATIONS_FAILDED |
    typeof SYNCHRO_DOWNLOAD_ONLINE_PATIENTS |
    typeof SYNCHRO_DOWNLOAD_ONLINE_PATIENTS_FAILDED |
    typeof SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS |
    typeof SYNCHRO_DOWNLOAD_ONLINE_DELETED_PATIENTS_FAILDED |
    typeof SYNCHRO_FULL_SUCCESS |
    typeof SYNCHRO_FULL_FAILDED;

export type AuditEventMessage = string;
